version: 2
jobs:
  build:
    parallelism: 3
    docker:
      - image: circleci/golang:1.10
    steps:
      - checkout
      - run: ci/dependencies.sh
      - run: ci/install.sh
      - run: ci/test.sh
      - run: ci/report.sh
      - run: ci/uninstall.sh
      - run: ci/cleanup.sh
      - store_artifacts:
          path: /tmp/artifacts
